### ISSUE TITLE
when you have more than 3 homes without contributor ranks you can still move them even if you cannot set them (RoMich02)

### ISSUE THREAD

**Issue by Bombniks** [PirateCraft/dev#156] opened 2021-06-29 14:32 UTC
### Describe the bug

When you get a contributor rank you can get up to 5 homes with the current max one(captain), when you lose the rank you are supposed to keep the homes but have no option to re-set them. Turns out you can actually re-set them even without a rank if you don't delete the home prior.

### To Reproduce

Get max homes, then try to relocate an existing home. Example is if you have a home named "a" do /sethome a without deleting it prior and without a contributor rank.

### Time and Date

15:12 29/6/2021

### Screenshots/Videos

https://user-images.githubusercontent.com/84421181/123816158-bfbc9780-d8ff-11eb-876c-8ddf5a04b415.mp4

**Comment by TomLewis** [comment] 2021-11-09 14:26
Yup.

Not a bug, just no logic to think how to resolve this, we will be moving to a GUI based home at some point, where I have to import all homes from everyone into it (yay thats going to be fun) at which point I can re-look at a method for limits, but its not the end of the world.

**Closed by TomLewis** 2021-11-09 14:26 UTC
Labels: bug, Survival
