### ISSUE TITLE
Warp South stockman doesn't allow mule purchase (M00SE_CABOOSE)

### ISSUE THREAD

**Issue by IwanIDev** [PirateCraft/dev#100] opened 2020-12-09 18:56 UTC
**Describe the bug** *(A clear and concise description of what the bug is)*:
The stockman at /warp south appears to sell mules, however the item cannot be purchased.

**To Reproduce** *(Steps to reproduce the behavior)*:
1. Travel to /warp south
2. Go to stockman
3. Attempt to purchase mule

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
First reported 6.12.2020 at 19:53 GMT+1

**Screenshots/Videos (Delete if not needed)** *(If applicable, add screenshots/videos to help explain your problem)*:
![Image of Issue](https://cdn.discordapp.com/attachments/744927959764434974/785217904190029844/image0.jpg)

**Comment by TomLewis** [comment] 2020-12-10 09:34
Dupe of #98 
Closed.

**Closed by TomLewis** 2020-12-10 09:34 UTC
Labels: Survival, bug
