### ISSUE TITLE
The vote crate is glitching and isnt giving out the XP boosts when won as a prize

### ISSUE THREAD

**Issue by CreatingWithKass** [PirateCraft/dev#43] opened 2020-09-07 15:28 UTC
**Describe the bug** *(A clear and concise description of what the bug is)*:
When a player uses a key at the vote crate and wins an XP Boost, it does not give the player the boost. It shows the win and then the player gets nothing, but still loses the key. 

**To Reproduce** *(Steps to reproduce the behavior)*:
Vote and then spend the keys at the crates. If the prize is an XP Boost, the player will get nothing. 

**Time and Date** *(If applicable, add the time (in GMT+1) and date (DD.MM.YYYY) of the issue)*:
09/05/2020 7:52 p.m. GMT+1

**Comment by TomLewis** [comment] 2020-09-08 09:22
Is this not a dupe of #38 and #37 which was fixed already?

**Closed** 2022-02-10 15:15 UTC
Labels: bug, Survival
